// Mocks generated by Mockito 5.4.2 from annotations
// in dashboard_breeds/test/blocs/dogs_images_test/dogs_images_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dashboard_breeds/models/breed_model.dart' as _i7;
import 'package:dashboard_breeds/models/dog_image_model.dart' as _i3;
import 'package:dashboard_breeds/models/dog_images_model.dart' as _i4;
import 'package:dashboard_breeds/repositories/breeds_repository.dart' as _i5;
import 'package:dashboard_breeds/services/breeds_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBreedsApiService_0 extends _i1.SmartFake
    implements _i2.BreedsApiService {
  _FakeBreedsApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDogImageModel_1 extends _i1.SmartFake implements _i3.DogImageModel {
  _FakeDogImageModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDogImagesModel_2 extends _i1.SmartFake
    implements _i4.DogImagesModel {
  _FakeDogImagesModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BreedsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedsRepository extends _i1.Mock implements _i5.BreedsRepository {
  MockBreedsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BreedsApiService get service => (super.noSuchMethod(
        Invocation.getter(#service),
        returnValue: _FakeBreedsApiService_0(
          this,
          Invocation.getter(#service),
        ),
      ) as _i2.BreedsApiService);

  @override
  _i6.Future<List<_i7.BreedModel>> breedsList() => (super.noSuchMethod(
        Invocation.method(
          #breedsList,
          [],
        ),
        returnValue: _i6.Future<List<_i7.BreedModel>>.value(<_i7.BreedModel>[]),
      ) as _i6.Future<List<_i7.BreedModel>>);

  @override
  _i6.Future<_i3.DogImageModel> randomBreedImage(String? breed) =>
      (super.noSuchMethod(
        Invocation.method(
          #randomBreedImage,
          [breed],
        ),
        returnValue: _i6.Future<_i3.DogImageModel>.value(_FakeDogImageModel_1(
          this,
          Invocation.method(
            #randomBreedImage,
            [breed],
          ),
        )),
      ) as _i6.Future<_i3.DogImageModel>);

  @override
  _i6.Future<_i4.DogImagesModel> breedImagesList(String? breed) =>
      (super.noSuchMethod(
        Invocation.method(
          #breedImagesList,
          [breed],
        ),
        returnValue: _i6.Future<_i4.DogImagesModel>.value(_FakeDogImagesModel_2(
          this,
          Invocation.method(
            #breedImagesList,
            [breed],
          ),
        )),
      ) as _i6.Future<_i4.DogImagesModel>);

  @override
  _i6.Future<_i3.DogImageModel> randomSubBreedImage(
    String? breed,
    String? subBreed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #randomSubBreedImage,
          [
            breed,
            subBreed,
          ],
        ),
        returnValue: _i6.Future<_i3.DogImageModel>.value(_FakeDogImageModel_1(
          this,
          Invocation.method(
            #randomSubBreedImage,
            [
              breed,
              subBreed,
            ],
          ),
        )),
      ) as _i6.Future<_i3.DogImageModel>);

  @override
  _i6.Future<_i4.DogImagesModel> subBreedImagesList(
    String? breed,
    String? subBreed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #subBreedImagesList,
          [
            breed,
            subBreed,
          ],
        ),
        returnValue: _i6.Future<_i4.DogImagesModel>.value(_FakeDogImagesModel_2(
          this,
          Invocation.method(
            #subBreedImagesList,
            [
              breed,
              subBreed,
            ],
          ),
        )),
      ) as _i6.Future<_i4.DogImagesModel>);
}
