// Mocks generated by Mockito 5.4.2 from annotations
// in dashboard_breeds/test/repositories/breeds_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dashboard_breeds/models/breed_model.dart' as _i7;
import 'package:dashboard_breeds/models/dog_image_model.dart' as _i3;
import 'package:dashboard_breeds/models/dog_images_model.dart' as _i4;
import 'package:dashboard_breeds/services/breeds_api_service.dart' as _i5;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDogImageModel_1 extends _i1.SmartFake implements _i3.DogImageModel {
  _FakeDogImageModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDogImagesModel_2 extends _i1.SmartFake
    implements _i4.DogImagesModel {
  _FakeDogImagesModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BreedsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBreedsApiService extends _i1.Mock implements _i5.BreedsApiService {
  MockBreedsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);

  @override
  set client(_i2.Client? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<List<_i7.BreedModel>> getBreedList() => (super.noSuchMethod(
        Invocation.method(
          #getBreedList,
          [],
        ),
        returnValue: _i6.Future<List<_i7.BreedModel>>.value(<_i7.BreedModel>[]),
      ) as _i6.Future<List<_i7.BreedModel>>);

  @override
  _i6.Future<_i3.DogImageModel> getRandomBreedImage(String? breed) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomBreedImage,
          [breed],
        ),
        returnValue: _i6.Future<_i3.DogImageModel>.value(_FakeDogImageModel_1(
          this,
          Invocation.method(
            #getRandomBreedImage,
            [breed],
          ),
        )),
      ) as _i6.Future<_i3.DogImageModel>);

  @override
  _i6.Future<_i4.DogImagesModel> getBreedImagesList(String? breed) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBreedImagesList,
          [breed],
        ),
        returnValue: _i6.Future<_i4.DogImagesModel>.value(_FakeDogImagesModel_2(
          this,
          Invocation.method(
            #getBreedImagesList,
            [breed],
          ),
        )),
      ) as _i6.Future<_i4.DogImagesModel>);

  @override
  _i6.Future<_i3.DogImageModel> getRandomSubBreedImage(
    String? breed,
    String? subBreed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomSubBreedImage,
          [
            breed,
            subBreed,
          ],
        ),
        returnValue: _i6.Future<_i3.DogImageModel>.value(_FakeDogImageModel_1(
          this,
          Invocation.method(
            #getRandomSubBreedImage,
            [
              breed,
              subBreed,
            ],
          ),
        )),
      ) as _i6.Future<_i3.DogImageModel>);

  @override
  _i6.Future<_i4.DogImagesModel> getSubBreedImagesList(
    String? breed,
    String? subBreed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubBreedImagesList,
          [
            breed,
            subBreed,
          ],
        ),
        returnValue: _i6.Future<_i4.DogImagesModel>.value(_FakeDogImagesModel_2(
          this,
          Invocation.method(
            #getSubBreedImagesList,
            [
              breed,
              subBreed,
            ],
          ),
        )),
      ) as _i6.Future<_i4.DogImagesModel>);
}
